FROM python:3.9-slim AS backend

WORKDIR /app
COPY . /app/

RUN pip install --no-cache-dir -r requirements.txt


ENV GOOGLE_APPLICATION_CREDENTIALS="authentication.json"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
